POSTGRESQL_HOST: 192.168.0.194
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: users_db
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: Password123

ACTIVE_PROFILE: dev
CONTAINER_PORT: 8085

EMAIL_HOST: 192.168.0.194
EMAIL_PORT: 1025
EMAIL_ID: "sender@mail.com"
EMAIL_PASSWORD: "Password123"
VERIFY_EMAIL_HOST: http://localhost:8085

JWT_EXPIRATION: 432_000_000 # 5 days
JWT_SECRET: ${SECRET}

BASE_URL: /api/v1

ADMIN_PASSWORD: ${ADMIN_PASSWORD}

##mail
#EMAIL_HOST: smtp.gmail.com
#EMAIL_PORT: 587
#EMAIL_ID: davidtnko@gmail.com
#EMAIL_PASSWORD:
#VERIFY_EMAIL_HOST: http://localhost:8085


