spring:
  config:
    activate:
      on-profile: dev-h2

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Отключаем Redis в профиле для локальной разработки
redis:
  host: localhost
  port: 6379
  password: ""
  enabled: false

jwt:
  secret: dev-secret-key
  expiration-time: 3600000

