spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test_user
    password: test_password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
