#Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: Password123
POSTGRESQL_HOST: 192.168.1. #todo
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase


#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

#mail
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:8085