spring:
  data:
    redis:
      host: localhost
      port: 6379

  config:
    activate:
      on-profile: dev-local

  datasource:
    url: jdbc:postgresql://localhost:5432/tsp
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      schema: tsp
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS tsp
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
