spring:
  application:
    name: user-service
  profiles:
    active: dev-local


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

#eureka:
#  client:
#    enabled: false
#
#feign:
#  hystrix:
#    enabled: true
#
#logging:
#  level:
#    org.springframework: INFO

api:
  endpoint:
    base-url: /api/v1

app:
  default:
    role: ROLE_USER
