#Database
POSTGRESQL_HOST: 192.168.0.90
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docdatabase
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: Password123

#Server
ACTIVE_PROFILE: dev
CONTAINER_PORT: 8085

#mail
EMAIL_HOST: localhost
EMAIL_PORT: 1025
EMAIL_ID: "user@mail.com"
EMAIL_PASSWORD: "Password123"
VERIFY_EMAIL_HOST: http://localhost:8085


