spring:
  config:
    activate:
      on-profile: dev-containers

  datasource:
    url: jdbc:postgresql://postgres-container:5432/userdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Redis для хранения access токенов
redis:
  host: redis-container
  port: 6379
  password: ""

jwt:
  secret: dev-containers-secret-key
  expiration-time: 3600000


