blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/davidav-k/task-management-platform/discussions
    about: Ask any general questions or start a discussion about the project.
