version: '3'
services:
  user-service:
    build: ../backend/user-service
    ports:
      - "8081:8081"
  task-service:
    build: ../backend/task-service
    ports:
      - "8082:8082"
  notification-service:
    build: ../backend/notification-service
    ports:
      - "8083:8083"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
