services:
  postgresdb:
    container_name: postgrescontainer
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgresvolume:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.dl/schema.sql

  pgadmin:
    container_name: pgadmincontainer
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DEFAULT_ADDRESS: 6000
      PGADMIN_LISTEN_PORT: 6000
    expose:
      - 6000
    ports:
      - "7000:6000"
    volumes:
      - pgadminvolume:/var/lib/pgadmin

  mailhog:
    container_name: mailhogcontainer
    image: mailhog/mailhog
    restart: always
    expose:
      - 1025
      - 8025
    ports:
      - "1025:1025" # SMTP-сервер для отправки почты
      - "8025:8025" # Веб-интерфейс для просмотра писем

volumes:
  pgadminvolume:
  postgresvolume:
