services:
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tsp
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"