# name: Build and Test Microservices

# on:
#   push:
#     branches:
#       - main
#       - develop

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 17
#       uses: actions/setup-java@v1
#       with:
#         java-version: '17'

#     - name: Build User Service
#       run: mvn clean install -f ./backend/user-service/pom.xml
#     - name: Test User Service
#       run: mvn test -f ./backend/user-service/pom.xml

#     - name: Build Task Service
#       run: mvn clean install -f ./backend/task-service/pom.xml
#     - name: Test Task Service
#       run: mvn test -f ./backend/task-service/pom.xml
